include themes/noctalia.conf

font_size        14
font_family      family="Fira Code"
bold_font        auto
italic_font      auto
bold_italic_font auto

confirm_os_window_close 0

open_url_with firefox

# disable tab changing shortcut because of conflict with micro 
map ctrl+shift+left no_op
map ctrl+shift+right no_op
